---
title: "20230404_Lab_fuctions"
author: "Kenta"
date: "2023-04-11"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../output/")
```

# Load Libraries

```{r}
library(tidyverse)
library(here)
library(palmerpenguins)
library(PNWColors)
```


# Read the Data

```{r}
view(penguins)
```

# Function to plot 
```{r}
penguin_plot<-function(data = penguins, x, y, points) {if(points == "alpha") { 
  pal<-pnw_palette("Starfish",3, type = "continuous") 
ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+  
  theme_bw()
}else{if(points == "beta"){ pal<-pnw_palette("Bay",3, type = "discrete") 
ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+  
  theme_bw()
}else{if(points == "omega"){pal<-pnw_palette("Moth",3, type = "discrete") 
ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+  
  theme_bw()
}
}
}
}
```

# Plotting Data

```{r}
penguin_plot(x = body_mass_g,
       y = bill_length_mm,
       points= "alpha")
```


```{r}
penguin_plot(x = body_mass_g,
       y = bill_length_mm,
       points = "beta")
```

```{r}
penguin_plot(x = body_mass_g,
       y = bill_length_mm,
       points = "omega")
```

