---
title: "20230425_HW_for_loop"
author: "Kenta"
date: "2023-04-25"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../output/")
```

# Loading the Library
```{r}
library(tidyverse)
library(here)
```

# For looping the data

```{r}
homework_path <- here("Week_12", "data", "homework")

Mudkip <- dir(path = homework_path,pattern = ".csv")

homework_data<-data.frame(matrix(nrow = length(Mudkip), ncol = 5))

colnames(homework_data)<-c("filename","mean_temp_c", "sd_temp_c", "mean_light_intensity", "sd_light_intensity")

raw_mudkip<-read_csv(paste0(homework_path,"/",Mudkip[1]))

mean_temp_c<-mean(raw_mudkip$Temp.C, na.rm = TRUE)

for (i in 1:length(Mudkip)){ # loop over 1:3 the number of files 
  raw_data<-read_csv(paste0(homework_path,"/",Mudkip[i]))
  homework_data$filename[i]<-Mudkip[i]
  homework_data$mean_temp_c[i]<- mean(raw_mudkip$Temp.C, na.rm = TRUE)
  homework_data$mean_light_intensity[i]<- mean(raw_mudkip$Intensity.lux, na.rm = TRUE)
  homework_data$sd_temp_c[i]<- sd(raw_mudkip$Temp.C, na.rm = TRUE)
  homework_data$sd_light_intensity[i]<- sd(raw_mudkip$Intensity.lux, na.rm = TRUE)
} 

homework_data
```

# For map()ing the data

```{r}
homework_path <- here("Week_12", "data", "homework")
vulpix <- dir(path = homework_path,pattern = ".csv",  full.names = TRUE)

homework_data_map<-vulpix %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename")%>% 
  group_by(filename) %>%
  summarise(mean_temp_c = mean(Temp.C, na.rm = TRUE),
            mean_light_intensity = mean(Intensity.lux,na.rm = TRUE),
            sd_temp_c = sd(Temp.C, na.rm = TRUE),
            sd_light_intensity = sd(Intensity.lux,na.rm = TRUE)) 

homework_data_map
```


