---
title: "20230302Homework"
author: "Kenta"
date: "2023-03-02"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../output/")
```

#Load libraries

```{r}
library(tidyverse)
library(here)
library(kableExtra)
library(lubridate)
library(palmerpenguins)
library(dplyr)
library(ggplot2)
```

# Inspect Data
```{r}
ChemData <- read_csv(here("Week_04","Data","chemicaldata_maunalua.csv")) 
```

# Plot

```{r}
view(ChemData)
the_difference_between_daytime <- ChemData %>% 
  drop_na() %>% 
  separate(col = Tide_time, 
           into = c("Tide","Time"), 
           sep = "_", 
           remove = FALSE) %>%
  pivot_longer(cols = Temp_in:percent_sgd, 
               names_to = "Variables", 
               values_to = "Values")%>%
  select(Site, Time, Variables, Values)%>%
  ggplot(aes(x=Time,
             y=Values,
             color=Time))+
  geom_boxplot()+
  facet_wrap(~Variables, scales = "free")
  



view(the_difference_between_daytime)
the_difference_between_daytime

```

# Table
```{r}
the_difference_between_daytime %>%
  group_by(Time) %>%
  summarise(Variablesmean = mean(Variables, na.rm = TRUE)) %>%
  kbl() %>%
  kable_classic() %>%
  row_spec(2, bold = T, color = "white", background = "red") %>%
  kable_styling(full_width = FALSE)
```

