---
title: "Penguins"
author: "Kenta"
date: "2023-03-02"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../output/")
```

# Load Library
```{r}
library(tidyverse)
library(here)
library(palmerpenguins)
library(kableExtra)
```

# Inspect the data
```{r}
glimpse(penguins)
```


# Making plot
```{r penguin, fig.asp=1.2, fig.align='center', fig.cap="This my penguin figure"}

ymd("2021-02-24")
datetimes<-c("02/24/2021 22:22:20",
             "02/25/2021 11:21:10",
             "02/26/2021 8:01:52")

datetimes <- mdy_hms (datetimes)
penguins%>%
  ggplot(aes(x=bill_length_mm,
             y = bill_depth_mm,
             color = species)) +
  geom_point()+
  geom_smooth(method = "lm") + #add a linear regression
  labs(x = "Bill length",
       y = "Bill depth",
       color = "Species") +
  theme_grey()
```

# Tables

| Time  | Session | Topic    |
|:------|:-------:|---------:|
| _left_ | _center_| _right_ |
| 01:00  | 1       | Anatomy |
| 01:50  |         | *Break* |
| 02:00  | 2       | Tables  |
| 02:45  |         | *Break* |

```{r}
penguins %>%
  group_by(species) %>%
  summarise(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl() %>%
  kable_classic() %>%
  row_spec(2, bold = T, color = "white", background = "red") %>%
  kable_styling(full_width = FALSE)
```


